EXTDEF_ENABLE_EMAIL = True
EXTDEF_EMAIL_TOADDR = "*********@gmail.com"
EXTDEF_EMAIL_FROMADDR = "rpip47646@gmail.com"
EXTDEF_EMAIL_BODY = "PFA"
EXTDEF_EMAIL_SUBJECT = "EVENT NOTIFICATION"
EXTDEF_EMAIL_GMAIL_KEY = "**************"

EXTDEF_ENABLE_SMS = False
EXTDEF_SMS_APIKEY = "******************************************************************************" 
EXTDEF_SMS_BODY = "event detected"
EXTDEF_SMS_TONUMBER = "************"

EXTDEF_TOSEND_PATH = "C:/Users/..."
EXTDEF_EVENT_LOG = "eventlog.txt"

EXTDEF_UPDATE_IMAGE_FLAG = False
EXTDEF_EVENT_CHECK_FRAMES = 50
EXTDEF_SUSTAINED_EVENT_VERIFICATION_RUNS = 5
EXTDEF_NOTIFICATION_GAP_IN_SECONDS = 60
